### ISSUE TITLE
Minor additions

### ISSUE THREAD

**Issue by bgazzera** [bonndan/ansible-userguide-pdf#1]
Hi there!

First of all very many thanks for putting this generator together. I find it essential for anyone learning Ansible, as browsing through the docs site is a pain.

I couple of minor corrections / additions to the README.

First there is a typo, where:
`python build_site.py ../ansible/docsite/rst/`
should be:
`python build-site.py ../ansible/docsite/rst/`

Also when I first tried to build, pdflatex complained
`! LaTeX Error: File 'cmap.sty' not found.`
after some research I found that I was missing the texlive-latex-recommended package.

If you don't mind, I can make this corrections and send a PR your way.

Thanks again

**Comment by bonndan** [comment]
A PR would be great, thanks!

**Comment by bonndan** [comment]
@bgazzera If I remember correctly there were some nasty line break issues in the generated doc (maybe in code sections). Do you know any LaTeX tricks to circumvent this?

**Comment by bgazzera** [comment]
No, sorry and yes some lines are overflowing. 
I see many of these in pdflatex run:

```
Overfull \hbox (14.79999pt too wide) in paragraph at lines 47794--47794
```

But LaTeX is black magic for me. 

In fact I've been struggling to get all the modules pages correctly into the PDF. So far I have an 808 pages doc with all the pages in, but with an incorrect TOC. I would love to be able to get this just right as I think that it is very useful. I could contact the maintainer of the Ansible docs to see if they are interested and point them at yout repo, if you don't mind.

I've also managed to get the file output as EPUB as I mostly read on a Kindle.

**Comment by bonndan** [comment]
The toc might fix in a second run (http://tex.stackexchange.com/questions/107967/need-to-typeset-twice-for-correct-compile). 

Although I brought up the topic, let's open another ticket for the line break thing.
